version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - "mongodb:/data/db"
    ports:
      - '27017:27017'
  backend:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: npm run start:dev

volumes:
  mongodb:
    driver: local    